# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca0c4444bc389012fa29d523a5f2ed491bf9df5e5c52791e39cbbda0c2cf52bc50f33b59cd55bc79f53edbc3c3dd56612a506490d5f57bf70fddef4b713d744

test:
  secret_key_base: f2c433f915f434e8c2f5d11a7be300eb79b97a6eae2ec565169fb61a3802fd9b08ed9d1b1cbeb89d3d648695f2c15e9839ee25f97bc3371244afad1e23ded419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
